import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased scroll-smooth flex min-h-svh flex-col text-gray-950 bg-gray-100 dark:bg-gray-950 dark:text-gray-200`}
      >
        <ThemeProvider>
          <Navbar />
          <main className="container mx-auto w-full flex-1 p-4">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
